//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class paf_ParDefs
    {
        public string paf_ParNm { get; set; }
        public string paf_ParDesc { get; set; }
        public string paf_ParValueUOM { get; set; }
        public int paf_BeforeSep { get; set; }
        public int paf_AfterSep { get; set; }
        public string paf_ValidValues { get; set; }
        public string paf_DefValue { get; set; }
        public int paf_Type { get; set; }
        public int paf_Alignm { get; set; }
        public int paf_Editable { get; set; }
        public Nullable<int> paf_DisplaySeqNr { get; set; }
        public Nullable<int> paf_DisplayWidth { get; set; }
        public string paf_ParUOM_TextId { get; set; }
        public string paf_DisplayToUser { get; set; }
        public Nullable<bool> paf_IsRequired { get; set; }
        public Nullable<int> paf_Column { get; set; }
        public bool paf_IsStandardPar { get; set; }
    }
}
